server:
  port: 9100
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_shop?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: shop-service
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    id-type: 0
    capital-mode: true
    db-column-underline: true
    field-strategy: 1
    logic-delete-value: 1
    logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lordy.shop.shop_api.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true
  params:
    count:
      countSql
dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.lordy.shop.shop_service.service
  registry:
    address: nacos://127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

