server:
  port: 10002

spring:
  application:
    name: login-log-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        login-log-topic: {destination: login-log-topic, content-type: text/plain, group: login-log-group, consumer.maxAttempts: 1, consumer.orderly: true}

dubbo:
  consumer:
    check: false
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: log-service
  protocol:
    port: -1
    name: dubbo
management:
  endpoints:
    web:
      exposure:
        include: '*'
